# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tamas Lang
tagline:          ''
description:      'Repositories: <a href="https://github.com/tamaslang" target="_blank">Github</a>.<br/>Profile: <a href="https://uk.linkedin.com/in/tamaslang" target="_blank">LinkedIn</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Tamas Lang'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tamaslang
