# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Talang Soft Limited
tagline:          'Enthusiastic Development'
description:      'Enthusiastic Development'
url:              http://talangsoft.org
baseurl:          /

author:
  name:           'Talang Lang'
  url:            http://talangsoft.org

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tamaslang
