# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Talang Soft Limited
tagline:          'Happy Coding'
description:      '--- Happy Coding ---'
url:              http://talangsoft.org
baseurl:          /

author:
  name:           'Tamas Lang'
  url:            http://talangsoft.org

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tamaslang
